- name: "Configure all i3status behavior in '{{ i3status_config_file_path }}'"
  ansible.builtin.template:
    dest: "{{ i3status_config_file_path }}"
    src: "config.j2"
    owner: "{{ i3status_user_name }}"
    mode: '644'
    force: yes
  become: true
  become_user: root

